Bakery/Models/Treat.cs
using System.ComponentModel.DataAnnotations;

namespace Bakery.Models;

public class Treat
{
  public int TreatId { get; set; }
  [Required(ErrorMessage = "The treat's name can't be empty")]
  public string Name { get; set; }
  public ApplicationUser User { get; set; }
  public List<FlavorTreat> JoinEntities { get; }
}

Bakery/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

using Bakery.Models;

namespace Bakery.Controllers;

[Authorize]
public class TreatsController : Controller
{
  private readonly BakeryContext _db;

  public TreatsController(BakeryContext db)
  {
    _db = db;
  }

  public ActionResult Index()
  {
    List<Treat> model = _db.Treats.ToList();
    return View(model);
  }
  public ActionResult Create()
  {
    return View();
  }
  [HttpPost]
  public ActionResult Create(Treat treat)
  {
    if (!ModelState.IsValid)
    {
      return View(treat);
    }
    else
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
  public ActionResult Details(int id)
  {
    Treat thisTreat = _db.Treats
      .Include(treat => treat.JoinEntities)
      .ThenInclude(join => join.Flavor)
      .FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }
  public ActionResult AddFlavor(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
    return View(thisTreat);
  }

  [HttpPost]
  public ActionResult AddFlavor(Treat treat, int flavorId)
  {
#nullable enable
    FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
    if (joinEntity == null && flavorId != 0)
    {
      _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treat.TreatId, FlavorId = flavorId });
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = treat.TreatId });
  }
  [HttpPost]
  public ActionResult DeleteJoin(int joinId)
  {
    FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
    _db.FlavorTreats.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
  public ActionResult Edit(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

  [HttpPost]
  public ActionResult Edit(Treat treat)
  {
    _db.Treats.Update(treat);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
  public ActionResult Delete(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    _db.Treats.Remove(thisTreat);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
}

Bakery/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Add a flavor</h2>

<h4>Add a flavor to this item: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to treat", "Details", new { id = Model.TreatId})</p>

Bakery/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h4>Add a new treat</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new treat" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all treats", "Index")</p>

Bakery/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Bakery/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models
@model Bakery.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This treat does not have any flavors yet!</p>
}
else
{
  <h4>This treat has the following flavors:</h4>
  <ul>
    @foreach(FlavorTreat join in Model.JoinEntities)
    {
      <li>Flavor: @join.Flavor.Name</li>
      @using (Html.BeginForm("DeleteJoin", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })</p>

<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>

Bakery/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Treat

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to treat", "Details", new { id = Model.TreatId })</p>

Bakery/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models;

<h1>Treats</h1>

@if (@Model.Count == 0)
{
  <h3>No treats have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new treat", "Create")</p>