Bakery/Models/Flavor.cs
using System.ComponentModel.DataAnnotations;

namespace Bakery.Models;

public class Flavor
{
  public int FlavorId { get; set; }
  [Required(ErrorMessage = "The flavor's name can't be empty")]
  public string Name { get; set; }
  public ApplicationUser User { get; set; }
  public List<FlavorTreat> JoinEntities { get; }
}

Bakery/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;


using Bakery.Models;

namespace Bakery.Controllers;

[Authorize]
public class FlavorsController : Controller
{
  private readonly BakeryContext _db;
  private readonly UserManager<ApplicationUser> _userManager;

  public FlavorsController(BakeryContext db, UserManager<ApplicationUser> userManager)
  {
    _userManager = userManager;
    _db = db;
  }

  public ActionResult Index()
  {
    List<Flavor> model = _db.Flavors.ToList();
    return View(model);
  }
  public ActionResult Create()
  {
    return View();
  }

  [HttpPost]
  public async Task<ActionResult> Create(Flavor flavor)
  {
    if (!ModelState.IsValid)
    {
      return View(flavor);
    }
    else
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
  public ActionResult Details(int id)
  {
    Flavor thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }
  public ActionResult AddTreat(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
    return View(thisFlavor);
  }

  [HttpPost]
  public ActionResult AddTreat(Flavor flavor, int treatId)
  {
#nullable enable
    FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
#nullable disable
    if (joinEntity == null && treatId != 0)
    {
      _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId });
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = flavor.FlavorId });
  }
  [HttpPost]
  public ActionResult DeleteJoin(int joinId)
  {
    FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
    _db.FlavorTreats.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
  public ActionResult Edit(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

  [HttpPost]
  public ActionResult Edit(Flavor flavor)
  {
    _db.Flavors.Update(flavor);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
  public ActionResult Delete(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    _db.Flavors.Remove(thisFlavor);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
}

Bakery/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Add a treat</h2>

<h4>Add a treat to this item: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to flavor", "Details", new { id = Model.FlavorId})</p>

Bakery/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h4>Add a new flavor</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new flavor" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

Bakery/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Bakery/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models
@model Bakery.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This flavor does not have any treats yet!</p>
}
else
{
  <h4>This flavor has the following treats:</h4>
  <ul>
    @foreach(FlavorTreat join in Model.JoinEntities)
    {
      <li>Treat: @join.Treat.Name</li>
      @using (Html.BeginForm("DeleteJoin", "Flavors"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>

<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>

Bakery/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to flavor", "Details", new { id = Model.FlavorId })</p>

Bakery/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new flavor", "Create")</p>